### ISSUE TITLE
Build for osx-arm64?

### ISSUE THREAD

**Issue by hadim** [conda-forge/dftd3-python-feedstock#16]
### Comment:

I haven't seen any PR attempting to migrate to osx-arm64. Do you know if it's compatible with upstream or worth trying @conda-forge/dftd3-python ?

**Comment by hadim** [comment]
xref https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4608

**Comment by loriab** [comment]
Thanks for prompting and pursuing this, @hadim and @awvwgk .  It was on my todo list, too.

**Comment by awvwgk** [comment]
Completed with #17
