### ISSUE TITLE
PSA: dftd3 on windows may not install with other packages

### ISSUE THREAD

**Issue by loriab** [conda-forge/dftd3-python-feedstock#30]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

Thanks for re-enabling windows for dftd3! This more of a public service announcement than a bug report. It looks like the latest d3 (python or simple-dftd3) and d4 c-f packages cannot be installed together on windows. Below is a sample env.

I suspect that d3 is built to current standards, and it is psi4 and the other packages (win disabled on d4, so that is an old build) are the ones that need to catch up on c-f windows build conditions, so this is just posting info.

```
>CONDA_SUBDIR=win-64 conda create -n testd3asdf dftd3-python=1.2.0 dftd4-python -c conda-forge

Channels:
 - conda-forge
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package dftd3-python-1.2.0-py310hffdb705_1 requires libwinpthread >=12.0.0.r4.gg4f2fc60ca, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ dftd3-python 1.2.0**  is installable and it requires
│  └─ libwinpthread >=12.0.0.r4.gg4f2fc60ca , which requires
│     └─ msys2-conda-epoch <0.0a0 , which can be installed;
└─ dftd4-python is not installable because it requires
   └─ m2w64-gcc-libs, which requires
      └─ msys2-conda-epoch 20160418 , which conflicts with any installable versions previously reported.
```

### Installed packages

none

### Environment info

none

**Comment by awvwgk** [comment]
This is part of the migration running for [m2w64-ucrt](https://conda-forge.org/status/migration/?name=r-base44_and_m2w64-ucrt). Packages build before the migration are unfortunately not compatible with packages build after the migration.
